### ISSUE TITLE
Cannot sign in when running the program

### ISSUE THREAD

**Issue by chialiyu** [DoctaHsieh/Multiplayer-Game#13]
**Environment**
When I run the program and try to sign up, the sign up works, and the database saves it. If you try to sign up with the same user, it pushes the correct error message. However, when I try to sign in, the terminal throws an error.

**Steps to recreate**

1. Open your project folder in the command line
2. Open up your mongo bin file in a separate command line
3. In your mongo, run "mongo".
4. Run "use myGame"
5. In your project folder, run "node app.js".
6. Open up a browser and search "localhost:2000".
7. Type in a random username and password into the fields and press sign up.
8. Try signing in with the same account.
9..The error message should show up on the command line.

**Error message**
ReferenceError: res is not defined
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\app.js:59:4
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\app.js:32:4
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:73:24
    at AsyncResource.runInAsyncScope (async_hooks.js:187:9)
    at runInAsyncScope (C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:195:16)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongojs\lib\cursor.js:205:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\utils.js:674:5
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\cursor.js:250:9
    at handleCallback (C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\core\cursor.js:31:5)
    at C:\Users\Evan\IdeaProjects\Multiplayer Game\node_modules\mongodb\lib\core\cursor.js:680:38
```
code section
```

**Comment by chialiyu** [comment]
I added more log messages and here is the logic flow (same recreation steps):
Server started.
Server - addUser.
before db.account.insert
After db.account.insert

Database.savePlayerProgress --->?? 

At this point, the new user is not in the game so I don't think savePlayerProgress should be called. This might be the problem here.
